name: Baton Github Schedule

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  schedule:
    name: Baton diff Github permissions
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container registry
        uses: docker/login-action@v1
        env:
          GITHUB_USER: jirwin
          GITHUB_TOKEN: ${{ secrets.BATON_TOKEN }}
        with:
          registry: ghcr.io
          username: jirwin
          password: ${{ secrets.BATON_TOKEN }}
      - uses: actions/checkout@v3
      - run: "./.github/scripts/schedule.sh"
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          BATON_ORGS: quadlek
          BATON_TOKEN: ${{ secrets.BATON_TOKEN }}